### ISSUE TITLE
FormsSample still crashing with new version

### ISSUE THREAD

**Issue by v534** [xamarin/urho-samples#24]
Downloaded latest FormsSample (1.1.125), but it is still crashing as reported in #15. For example in XAP, clicking "Launch Sample", then navigating back with top back button,  then clicking "Launch Sample" again causes crash.

Also, Android back button still does not work.

**Comment by MichalPetryk** [comment]
@v534  please take a look at [#141](https://github.com/xamarin/urho/issues/141)

When you leave Page with Urho you should call Application.Exit() before. FormsSample doesn't do it.

I think it should resolve your problem.

**Comment by v534** [comment]
Thanks @MichalPetryk! Adding Applicatin.Exit() did the trick.

**Comment by EgorBo** [comment]
Fixed with https://github.com/xamarin/urho/commit/86010ea61d19536671d0c254870fb807b2cfcbf3

**Comment by DumDumin** [comment]
Well, I am a little bit confused. Should it work with new Release now? because when I leave the page with the urhosurface and reenter it, there is an exception thrown. If I use the Application.Exit() first, there is an Exception, which states that I cannot access a disposed object. But I cant find out which object exactly is disposed....
This is really frustrating guys, I hope there is a solution. Thanks

**Comment by MichalPetryk** [comment]
@DumDumin try to call UrhoSurface.OnDestroy() instead of Application.Exit() before leaving the page with urhosurface.

**Comment by DumDumin** [comment]
Thanks for the advise! That is working the first 2 times navigating to the page with the urhosurface. The third time there is no exception, but the app does not load the surface correctly and stops responding completly.

If I navigate back from the page with the urhosurface, it is only working if the newpage was cached before. If the new page needs to be created, there will be an unexepted exception..

By navigating I mean the following: I use a masterdetailpage and most pages are rootpages of their own navigation stack right now. So if a navigate to a new page a I swap the navigation stacks  (navigation page) by setting the detail page of the masterdetail page to the new page.

Is it possible that my navigation "style" makes any trouble because I cache the pages and change complete navigation stacks?

Thanks for any help!

**Comment by DumDumin** [comment]
I have some more Information for those Errors:
1. Urhosurface.OnDestroy() kills the app if new page hasnt been shown before...
        ->access a page before you go from urho to that page
2. StartUrhoApp() kills the app if Bluetooth is connected and urho has not been shown before
        ->access urhopage before connecting to bluetooth

The first Error occurs wether bluetooth is used or not.
I also tried to push the urhopage on an existing navigationstack: with that, there wont be the first error, because the page we go back to was shown before :D but the second error still occurs.

Thanks for any hints!
