### ISSUE TITLE
FormSample for UWP

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/urho-samples#9]
Can we have a demo using UrhoSharp in Xamarin.Forms for UWP. Thanks

**Comment by EgorBo** [comment]
@JimSEOW sure, stay tuned.

**Comment by JimSEOW** [comment]
Great Jobs for releasing UWP samples. Keep it up! Can u pls also include UWP samples in the Xamarin.Forms.  :-)

**Comment by CalicoBay** [comment]
Thanks for the UWP Feature Samples. The Data.pak file is missing from the repository and while it is educational to clone Urho3D and learn where it comes from it did take me a while. Thanks again.

**Comment by JimSEOW** [comment]
HI CalicoBay, are you learning to clone and build in Mac? With only Windows10, I tried Bash for Windows, but I could not go very far :-(  .

**Comment by CalicoBay** [comment]
Hi Jim and Egor,I want to use Urho3D with UWP. Got UWP FeatureSamples to run on a PC after I inserted Data.pak into the UWP directory. Also got them to run on JellyBean very easily. My problem now is running on a Lumia 950(Windows 10 Mobile). The Urho.dll is not in the right format. Urho.Samples.UWP.MainPage.RunGame(..) throws a BadImageFormatException. I was thinking that since Microsoft bought Xamarin, the Windows phone might be a priority but I guess not. Maybe the Urho.dll that NuGet delivers is the wrong one. I tried them all from the packages directory to no avail. Hope to get a Mac soon. I need a common 3D library for everything and Urho seems to fit the bill.

**Comment by CalicoBay** [comment]
Hi again Jim. About cloning and building Urho3D on a Windows 10 PC. Using the CMake extension in Visual Studio 2015 and the Wiki on GitHub it was reasonable to build the Urho3D library, samples and tools. Now I just have to figure out to extract a C# assembly from it. Historically I'm a C++ guy so I need to do some reading.

**Comment by CalicoBay** [comment]
I must be getting too old for this! I cloned https://github.com/urho3d/Urho3D.git on the above note. Turns out, though, that https://github.com/xamarin/urho.git is maybe what I should have. But it doesn't clone properly. Still unravelling.

**Comment by CalicoBay** [comment]
Submodule Urho3D of https://github.com/xamarin/urho.git was moved to https://github.com/xamarin/Urho3D.git. Just for anybody's information.

**Comment by JimSEOW** [comment]
HI CallcoBay, 
I continue this discussion in https://github.com/xamarin/urho/issues/113

**Comment by CalicoBay** [comment]
All I wanted to do was run UWP-FeatureSamples on Windows 10 and Windows 10 Mobile. That way I could decide whether Urho3D through Xamarin was a good solution for my needs. My specific question is, will a ARM binding of urho.dll be available through NuGet in the near future? Microsoft is touting Xamarin and rightly so.

**Comment by CalicoBay** [comment]
Will Xamarin's Urho3D ever run on a real Windows 10 Mobile device? Please!

**Comment by JimSEOW** [comment]
https://github.com/emscripten-ports/SDL2/tree/master/VisualC-WinRT/UWP_VS2015
http://urho3d.prophpbb.com/topic1724.html
